import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data0 = pd.read_csv('sensors\data\zero.txt', sep=' ')
x_ticks = np.arange(data0['wavelength'].min(), data0['wavelength'].max(), step=100)
y_ticks = np.arange(0, 105, step=25)

fig_0, ax = plt.subplots(3, 2)
plt.subplots_adjust(hspace=0.5)
ax[0, 0].plot(data0['wavelength'], data0['intensity'])
ax[0, 0].title.set_text('Нулевое измерение (вода)')
ax[0, 0].set_xticks(x_ticks) 
# ax[0, 0].set_yticks(y_ticks) 
# plt.show()
data1 = pd.read_csv('sensors\\data\\1__5.txt', sep=' ')
# fig_1 = plt.figure()
ax[0, 1].plot(data1['wavelength'], data1['intensity'])
ax[0, 1].title.set_text('Краситель концентрации 10^(-5)')
ax[0, 1].set_xticks(x_ticks)
ax[0, 1].set_yticks(y_ticks)
# plt.show()
data2 = pd.read_csv('sensors\\data\\5__5.txt', sep=' ')
# fig_2 = plt.figure()
ax[1, 0].plot(data2['wavelength'], data2['intensity'])
ax[1, 0].title.set_text('Краситель концентрации 5 * 10^(-5)')
ax[1, 0].set_xticks(x_ticks)
ax[1, 0].set_yticks(y_ticks)
# plt.show()
data3 = pd.read_csv('sensors\\data\\1__4.txt', sep=' ')
# fig_3 = plt.figure()
ax[1, 1].plot(data3['wavelength'], data3['intensity'])
ax[1, 1].title.set_text('Краситель концентрации 10^(-4)')
ax[1, 1].set_xticks(x_ticks)
ax[1, 1].set_yticks(y_ticks)
# plt.show()
data4 = pd.read_csv('sensors\\data\\5__4.txt', sep=' ')
#  = plt.figure()
ax[2, 0].plot(data4['wavelength'], data4['intensity'])
ax[2, 0].title.set_text('Краситель концентрации 5 * 10^(-4)')
ax[2, 0].set_xticks(x_ticks)
ax[2, 0].set_yticks(y_ticks)
fig_0.suptitle('Показания спектрофлюориметра для растворов красителя эозина.')
plt.show()